# Generated by Django 5.2.8 on 2026-07-01 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_tr', models.CharField(max_length=120)),
                ('summary_en', models.TextField()),
                ('summary_tr', models.TextField()),
                ('default_image', models.ImageField(upload_to='procedures/defaults/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=120)),
                ('title_tr', models.CharField(blank=True, max_length=120)),
                ('before_image', models.ImageField(upload_to='procedures/before/')),
                ('after_image', models.ImageField(upload_to='procedures/after/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='clinic.procedure')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
