# Generated by Django 5.2.8 on 2026-07-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedureimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='procedureimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='procedureimage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='procedureimage',
            name='title_tr',
        ),
    ]
