# Generated by Django 5.2.8 on 2026-07-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_chattemplatelanguage_chattemplatesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattemplatelanguage',
            name='flag',
            field=models.CharField(blank=True, help_text='Static path to flag image, e.g. portal/flags/united-kingdom.svg.', max_length=255),
        ),
        migrations.AddField(
            model_name='chattemplatelanguage',
            name='language_name',
            field=models.CharField(blank=True, help_text='Language label shown under the name, e.g. English.', max_length=120),
        ),
        migrations.AlterField(
            model_name='chattemplatelanguage',
            name='code',
            field=models.SlugField(help_text='URL slug, e.g. united-kingdom.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='chattemplatelanguage',
            name='name',
            field=models.CharField(help_text='Display name on the dashboard card, e.g. United Kingdom.', max_length=120),
        ),
    ]
