# Generated by Django 5.2.8 on 2026-07-10 13:28

import clinic.models
import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_chattemplatelanguage_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattemplatelanguage',
            name='flag',
        ),
        migrations.AddField(
            model_name='chattemplatelanguage',
            name='image',
            field=models.ImageField(blank=True, help_text='PNG or JPG card image stored under static/portal/languages/.', storage=django.core.files.storage.FileSystemStorage(base_url='/static/portal/languages/', location=pathlib.PureWindowsPath('C:/Users/POOYAN/programming/M_clinic_2/static/portal/languages')), upload_to=clinic.models.language_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='chattemplatelanguage',
            name='code',
            field=models.SlugField(help_text='URL slug, e.g. english.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='chattemplatelanguage',
            name='language_name',
            field=models.CharField(blank=True, help_text='Optional secondary language label.', max_length=120),
        ),
        migrations.AlterField(
            model_name='chattemplatelanguage',
            name='name',
            field=models.CharField(help_text='Display name on the dashboard card, e.g. English.', max_length=120),
        ),
    ]
