UI_TEXTS = {
    'en': {
        'brand_subtitle': 'Plastic Surgery',
        'home': 'Home',
        'login': 'Login',
        'logout': 'Logout',
        'add_procedure': 'Add Procedure',
        'manage_content': 'Manage Content',
        'add_images': 'Add New Before & After',
        'edit_procedure': 'Edit Procedure',
        'delete_procedure': 'Delete Procedure',
        'edit_image': 'Edit Image',
        'delete_image': 'Delete Image',
        'procedures': 'Popular Procedures',
        'view_details': 'View Details',
        'before_after': 'Before & After Samples',
        'before': 'Before',
        'after': 'After',
        'about_procedure': 'About Procedure',
        'no_samples': 'No before/after images yet.',
        'title_en_label': 'Title (English)',
        'title_tr_label': 'Title (Turkish)',
        'before_image_label': 'Before Image',
        'after_image_label': 'After Image',
        'section_upload_hint': 'Add one or more sections. Each section needs a title, before image, and after image.',
        'add_section': 'Add Another Section',
        'section_label': 'Section',
        'add_before_image': 'Add Before Image',
        'add_after_image': 'Add After Image',
        'remove_row': 'Remove',
        'nested_upload_hint': 'Each section has Before and After parts. You can add multiple titled images in each part.',
        'no_before_in_section': 'No before images in this section.',
        'no_after_in_section': 'No after images in this section.',
        'save': 'Save',
        'update': 'Update',
        'cancel': 'Cancel',
        'confirm_delete': 'Are you sure?',
        'content_dashboard': 'Content Dashboard',
        'gallery_count': 'Gallery Items',
        'pick_language': 'Language',
    },
    'tr': {
        'brand_subtitle': 'Plastik Cerrahi',
        'home': 'Ana Sayfa',
        'login': 'Giris',
        'logout': 'Cikis',
        'add_procedure': 'Yeni Islem Ekle',
        'manage_content': 'Icerik Yonetimi',
        'add_images': 'Yeni Once & Sonra Ekle',
        'edit_procedure': 'Islemi Duzenle',
        'delete_procedure': 'Islemi Sil',
        'edit_image': 'Gorseli Duzenle',
        'delete_image': 'Gorseli Sil',
        'procedures': 'Populer Islemler',
        'view_details': 'Detaylari Gor',
        'before_after': 'Once & Sonra Ornekleri',
        'before': 'Once',
        'after': 'Sonra',
        'about_procedure': 'Islem Hakkinda',
        'no_samples': 'Henuz once/sonra gorseli yok.',
        'title_en_label': 'Baslik (English)',
        'title_tr_label': 'Baslik (Turkish)',
        'before_image_label': 'Once Gorseli',
        'after_image_label': 'Sonra Gorseli',
        'section_upload_hint': 'Baslik, once ve sonra gorseli olan bir veya daha fazla section ekleyin.',
        'add_section': 'Yeni Section Ekle',
        'section_label': 'Section',
        'add_before_image': 'Once Gorseli Ekle',
        'add_after_image': 'Sonra Gorseli Ekle',
        'remove_row': 'Sil',
        'nested_upload_hint': 'Her section Before ve After bolumlerine sahiptir. Her bolume birden fazla baslikli gorsel ekleyebilirsiniz.',
        'no_before_in_section': 'Bu sectionda once gorseli yok.',
        'no_after_in_section': 'Bu sectionda sonra gorseli yok.',
        'save': 'Kaydet',
        'update': 'Guncelle',
        'cancel': 'Iptal',
        'confirm_delete': 'Emin misiniz?',
        'content_dashboard': 'Icerik Paneli',
        'gallery_count': 'Galeri Kayitlari',
        'pick_language': 'Dil',
    },
}


def global_context(request):
    current_lang = request.session.get('lang', 'en')
    if current_lang not in UI_TEXTS:
        current_lang = 'en'

    return {
        'current_lang': current_lang,
        'texts': UI_TEXTS[current_lang],
    }
